### ISSUE TITLE
手柄按键配置跟原版不正确

### ISSUE THREAD

**Issue by OrcaXS** [Ouroboros/ED6-FC-Steam-CN#1]
使用 Xbox 360 手柄时，Config 正常识别出手柄并适配按键，原版程序可以正常使用手柄，汉化版程序虽然能用手柄，但按键不正确而且地图一直在旋转。

**Comment by Ouroboros** [comment]
不太可能, 根本没有动到手柄的代码
试一下是不是因为强制了日文造成的
1. 把`DAT目录`和`ed6fc.text`改名再启动汉化版
2. 在`dll`目录下新建一个`lang_jpn.dll`的空文件, 再启动原版游戏

**Comment by OrcaXS** [comment]
我之前用了 DualShock 4 手柄配合 DS4Windows 模拟360手柄有问题，现在换回 Xbox One 手柄就没问题了。看来是 DS4Windows 可能跟游戏有奇怪的兼容性问题。
