### ISSUE TITLE
战斗结束后物品获得提示的语序不正确

### ISSUE THREAD

**Issue by Hintay** [Ouroboros/ED6-FC-Steam-CN#8]
目前为日语/英语语序，即“XXXXを受け取った。”，而在中文语序里应为“得到了XXXX。”
如图：
![](https://cdn.eosolo.com/other/ED6-1.jpg)

**Comment by Ouroboros** [comment]
这在以前SC也有过, 要改程序才能调整顺序, 问题不大就懒得改了
