### ISSUE TITLE
关于游戏更新导致无法启动一事

### ISSUE THREAD

**Issue by civilo** [Ouroboros/ED6-FC-Steam-CN#9]
如题，4月26日Steam版游戏发布了一个更新（patch note: http://steamcommunity.com/games/251150/announcements/detail/1297444164416583428 ），汉化游戏也因此无法启动了。

请问您是否有意拨冗更新汉化补丁？这个帖子并不是催促您更新，只是希望了解清楚，若该中文补丁会跟进的话，我就等您的更新，否则便玩英文版。顺致感谢。

**Comment by Ouroboros** [comment]
短时间内都不会再更新了

**Comment by Ouroboros** [comment]
已更新
